const fs = require('fs');
const path = require('path');
const jsonPath = path.join(__dirname, '..', 'wp-content', 'themes', 'organium-child', 'data', 'consulta-produtos.json');
const d = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

// ============================================================
// 7 ÓLEOS ESSENCIAIS
// ============================================================
const oleos = [
  {
    nome: "Lavanda (Lavandula angustifolia)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Meta-análise de 2021 (Kim et al.) demonstrou que a lavanda é superior ao placebo na redução da ansiedade (Hedges' g = -0,72) e depressão (Hedges' g = -0,43), com efeito substancial via aromaterapia. Revisão sistemática e meta-análise em rede de 2023 (Tan et al.), incluindo 44 ECRs com 3.419 pacientes, confirmou que a lavanda reduz significativamente os escores de ansiedade estado e traço.",
    nivel_evidencia: "Moderada-Alta",
    aplicacoes_clinicas: "Transtornos de ansiedade, insônia leve, sintomas depressivos, redução de estresse pré-operatório, promoção do relaxamento",
    dosagem: "Inalação: 2-3 gotas em difusor por 20-30 min; Tópica: 1-3% diluído em óleo carreador; Oral (Silexan/Lavela): 80-160 mg/dia de óleo essencial padronizado",
    modo_uso: "Aromaterapia por inalação direta ou difusor; aplicação tópica diluída em óleo carreador (2-3%) em têmporas, pulsos ou planta dos pés; banho aromático (5-8 gotas); massagem aromaterapêutica.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/34775136/", "https://pubmed.ncbi.nlm.nih.gov/37325306/"],
    contraindicacoes: ["Gestantes e lactantes (uso oral)", "Crianças menores de 2 anos (uso tópico direto)", "Hipersensibilidade conhecida a Lavandula spp.", "Uso oral concomitante com sedativos ou ansiolíticos sem orientação médica"],
    interacoes: "Pode potencializar o efeito de sedativos, benzodiazepínicos e barbitúricos. Uso oral pode interagir com anticoagulantes.",
    efeitos_colaterais: "Geralmente bem tolerado. Inalação: raramente cefaleia leve. Uso tópico: dermatite de contato em indivíduos sensíveis. Uso oral: distúrbios gastrointestinais leves, eructação.",
    origem: "Mediterrâneo (sul da França, Bulgária, Espanha)",
    principios_ativos: ["Linalol", "Acetato de linalila"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Alecrim (Rosmarinus officinalis)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Ensaio clínico randomizado com 144 participantes (Moss et al., 2003) demonstrou que a inalação do aroma de alecrim melhora significativamente a qualidade geral da memória e a memória secundária em adultos saudáveis. Os efeitos cognitivos foram correlacionados com os níveis plasmáticos de 1,8-cineol, principal constituinte absorvido, sugerindo mecanismos neuroquímicos distintos.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Melhoria da performance cognitiva, suporte à memória e atenção, aumento do estado de alerta, fadiga mental",
    dosagem: "Inalação: 3-4 gotas em difusor por 20-30 min; Tópica: 2-3% diluído em óleo carreador para massagem no couro cabeludo e têmporas",
    modo_uso: "Aromaterapia por difusor durante estudo ou trabalho; inalação direta (1-2 gotas no lenço); massagem tópica diluída em óleo carreador na nuca e têmporas.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/12690999/"],
    contraindicacoes: ["Gestantes (potencial efeito emenagogo)", "Epilépticos (contém cânfora e 1,8-cineol, que podem reduzir o limiar convulsivo)", "Crianças menores de 6 anos", "Hipertensos graves (uso excessivo)"],
    interacoes: "Pode interferir com medicamentos anticonvulsivantes. Potencial interação com anti-hipertensivos e anticoagulantes em doses elevadas.",
    efeitos_colaterais: "Uso tópico: irritação cutânea em peles sensíveis. Inalação excessiva: cefaleia, tontura. Ingestão em altas doses: convulsões, vômitos.",
    origem: "Região Mediterrânea (Portugal, Espanha, Marrocos, Tunísia)",
    principios_ativos: ["1,8-cineol", "Cânfora", "Ácido rosmarínico"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Tea Tree / Melaleuca (Melaleuca alternifolia)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Revisão sistemática de ensaios clínicos randomizados (Ernst & Huntley, 2000) identificou evidências promissoras para a eficácia do óleo de melaleuca no tratamento de acne e infecções fúngicas, com efeitos adversos geralmente leves e transitórios. Revisão abrangente de 2023 (Nascimento et al.) confirmou propriedades antibacterianas, anti-inflamatórias e antioxidantes, demonstrando redução de lesões inflamatórias na acne.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Acne vulgar, infecções fúngicas cutâneas (onicomicose, pé de atleta), feridas superficiais, antisséptico tópico",
    dosagem: "Tópica para acne: gel ou solução a 5% (concentrações de 5-15%); Antifúngico: solução a 25-50% para onicomicose; Antisséptico: 0,5-1% em formulações",
    modo_uso: "Aplicação tópica diluída diretamente nas lesões de acne (5% em gel); compressas em infecções fúngicas; adição a produtos de limpeza facial. NUNCA ingerir.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/10800248/", "https://pubmed.ncbi.nlm.nih.gov/37371994/"],
    contraindicacoes: ["USO EXCLUSIVAMENTE TÓPICO — NUNCA ingerir (toxicidade oral grave)", "Hipersensibilidade ao terpinen-4-ol ou outros constituintes", "Pele gravemente lesionada ou queimaduras extensas", "Crianças menores de 6 anos (uso tópico puro)"],
    interacoes: "Sem interações medicamentosas significativas conhecidas por via tópica.",
    efeitos_colaterais: "Dermatite de contato alérgica (especialmente com óleo oxidado), irritação cutânea leve, ressecamento da pele. Ingestão acidental: confusão, ataxia, depressão do SNC.",
    origem: "Austrália (Nova Gales do Sul)",
    principios_ativos: ["Terpinen-4-ol", "γ-terpineno", "α-terpineno"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Hortelã-Pimenta (Mentha x piperita)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Revisão sistemática e meta-análise de 2014 (Khanna et al.), com 9 estudos e 726 pacientes, demonstrou que cápsulas de óleo de hortelã-pimenta com revestimento entérico são significativamente superiores ao placebo na melhora global dos sintomas da SII (RR 2,23; IC 95% 1,78-2,81) e na redução da dor abdominal (RR 2,14; IC 95% 1,64-2,79). Efeitos adversos leves e transitórios, sendo a pirose o mais comum.",
    nivel_evidencia: "Moderada-Alta",
    aplicacoes_clinicas: "Síndrome do intestino irritável (SII), cefaleia tensional (uso tópico), dispepsia funcional, náusea",
    dosagem: "SII: 0,2-0,4 mL de óleo em cápsulas entéricas, 3x/dia antes das refeições; Cefaleia: solução a 10% em etanol aplicada nas têmporas; Inalação: 2-3 gotas para náusea",
    modo_uso: "Via oral em cápsulas com revestimento entérico para SII (30-60 min antes das refeições); aplicação tópica diluída nas têmporas e testa para cefaleia tensional; inalação direta para náusea e congestão nasal.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/24100754/"],
    contraindicacoes: ["Doença do refluxo gastroesofágico (DRGE) — pode relaxar o esfíncter esofágico", "Hérnia hiatal", "Cálculos biliares", "Crianças menores de 8 anos (risco de espasmo laríngeo pelo mentol)", "Gestantes (grandes doses)"],
    interacoes: "Pode inibir o CYP3A4, afetando o metabolismo de ciclosporina, sinvastatina e outros substratos. Interação potencial com antiácidos e inibidores de bomba de prótons (dissolução precoce da cápsula entérica).",
    efeitos_colaterais: "Pirose (efeito adverso mais comum), náusea leve, sensação de queimação perianal, eructação mentolada. Uso tópico excessivo: irritação cutânea.",
    origem: "Europa (híbrido de M. aquatica e M. spicata, cultivado globalmente)",
    principios_ativos: ["Mentol", "Mentona", "1,8-cineol"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Eucalipto (Eucalyptus globulus)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Revisão sistemática e meta-análise de 2022 (Her et al.), incluindo 6 ECRs com 1.857 participantes, demonstrou que produtos à base de eucalipto são mais eficazes que placebo na melhora dos sintomas gerais de tosse (RR 1,45; IC 95% 1,26-1,67) e na redução da frequência da tosse associada a infecções respiratórias superiores e bronquite. Sem efeitos adversos graves relatados.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Alívio sintomático de tosse em infecções respiratórias superiores e bronquite, descongestionante nasal, sinusite",
    dosagem: "Inalação: 3-6 gotas em água quente para vaporização, 2-3x/dia; Tópica: 1-3% em óleo carreador para fricção torácica",
    modo_uso: "Inalação de vapor (3-6 gotas em tigela de água quente, cobrir cabeça com toalha, 10-15 min); fricção torácica diluída em óleo carreador; uso em difusor ambiental; banho quente aromático.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/35294302/"],
    contraindicacoes: ["Crianças menores de 3 anos (risco de espasmo laríngeo e depressão respiratória)", "Asma grave (pode desencadear broncoespasmo)", "Aplicação direta no rosto de lactentes e crianças pequenas", "Gestantes no primeiro trimestre"],
    interacoes: "O 1,8-cineol pode induzir enzimas hepáticas (CYP1A2, CYP2B6), potencialmente alterando o metabolismo de fármacos como aminofilina e anfetaminas. Pode potencializar hipoglicemiantes.",
    efeitos_colaterais: "Inalação: irritação das mucosas em concentrações elevadas. Uso tópico: dermatite de contato. Ingestão acidental: náusea, vômitos, diarreia; doses tóxicas podem causar depressão do SNC e convulsões.",
    origem: "Austrália (Tasmânia), amplamente cultivado em Portugal, Espanha, Brasil e China",
    principios_ativos: ["1,8-cineol (eucaliptol)", "α-pineno", "Limoneno"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Bergamota (Citrus bergamia)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Revisão sistemática de 2017 (Mannucci et al.) avaliou 10 ensaios clínicos sobre Citrus bergamia, dos quais 6 avaliaram o óleo essencial para redução de estresse por aromaterapia. A análise indicou que a aromaterapia com bergamota pode ser segura e útil na redução de sintomas de estresse, embora com amostras pequenas e limitações metodológicas.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Redução de estresse e ansiedade por aromaterapia, promoção do bem-estar emocional",
    dosagem: "Inalação: 2-5 gotas em difusor por 15-30 min; Tópica: 0,5-1% diluído em óleo carreador (concentração baixa devido à fotossensibilidade); Banho: 3-5 gotas diluídas",
    modo_uso: "Aromaterapia via difusor ambiental; inalação direta; massagem aromaterapêutica com óleo diluído (usar versão sem bergapteno/FCF para aplicação cutânea). EVITAR exposição solar após uso tópico.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/27747942/"],
    contraindicacoes: ["Exposição solar ou UV até 12-18h após aplicação tópica (fotossensibilidade por furanocumarinas/bergapteno)", "Pele fotossensível ou com histórico de melanoma", "Gestantes e lactantes (uso oral)", "Crianças menores de 2 anos (uso tópico)"],
    interacoes: "As furanocumarinas (bergapteno) podem interagir com medicamentos fotossensibilizantes (tetraciclinas, fluoroquinolonas, retinoides). Potencial interação com medicamentos metabolizados pelo CYP3A4.",
    efeitos_colaterais: "Fotossensibilidade cutânea severa (fitofotodermatite com bergapteno), irritação cutânea em peles sensíveis. Versão FCF (sem furanocumarinas) reduz significativamente este risco.",
    origem: "Sul da Itália (Calábria)",
    principios_ativos: ["Limoneno", "Linalol", "Acetato de linalila", "Bergapteno"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Capim-Limão (Cymbopogon citratus)",
    nome_chines: "",
    categoria: "Óleo Essencial",
    categoria_slug: "oleo_essencial",
    estudos_resumo: "Estudos experimentais em humanos indicam que a inalação do óleo essencial de capim-limão reduz significativamente os escores de ansiedade estado e tensão subjetiva. O efeito ansiolítico é atribuído ao citral (geranial e neral), que compõe 65-85% do óleo, com mecanismo proposto via complexo receptor GABA(A)-benzodiazepínico. Atividade antimicrobiana de amplo espectro demonstrada contra bactérias gram-positivas, gram-negativas e fungos.",
    nivel_evidencia: "Baixa",
    aplicacoes_clinicas: "Ansiedade situacional (aromaterapia complementar), atividade antimicrobiana tópica, repelente de insetos, suporte à digestão",
    dosagem: "Inalação: 2-4 gotas em difusor por 15-30 min; Tópica: 1-2% diluído em óleo carreador; Chá (folhas, não óleo): 1-2 g de folhas secas em 150 mL de água",
    modo_uso: "Aromaterapia via difusor para ansiedade; inalação direta antes de procedimentos estressantes; uso tópico diluído como repelente; infusão das folhas para uso digestivo (não confundir com óleo essencial puro).",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/37325306/"],
    contraindicacoes: ["Gestantes (potencial efeito uterotônico)", "Lactantes", "Hipersensibilidade a gramíneas (Poaceae)", "Pele sensível ou danificada (uso tópico puro)"],
    interacoes: "Pode potencializar o efeito de sedativos e ansiolíticos. Potencial interação com hipoglicemiantes orais.",
    efeitos_colaterais: "Uso tópico: irritação cutânea, dermatite de contato alérgica. Inalação excessiva: cefaleia, tontura. Ingestão de óleo puro: irritação gastrointestinal.",
    origem: "Sudeste Asiático (Índia, Sri Lanka), amplamente cultivado em regiões tropicais (Brasil, Guatemala, África)",
    principios_ativos: ["Citral (geranial + neral)", "Mirceno", "Geraniol"],
    ingredientes: [],
    faq: []
  }
];

// ============================================================
// 9 PLANTAS MEDICINAIS
// ============================================================
const plantas = [
  {
    nome: "Valeriana (Valeriana officinalis)",
    nome_chines: "",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão sistemática e meta-análise de 2020 (60 estudos, n=6.894) concluiu que a valeriana pode melhorar a qualidade subjetiva do sono com tamanho de efeito moderado, especialmente quando utilizada a raiz inteira. Meta-análise anterior (2006, 16 estudos, n=1.093) mostrou benefício estatisticamente significativo na qualidade do sono (RR=1,8; IC 95% 1,2-2,9). Efeitos adversos infrequentes e leves.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Insônia leve a moderada; ansiedade leve; melhoria da qualidade do sono",
    dosagem: "300-600 mg de extrato padronizado ou 2-3 g de raiz seca, 30-60 minutos antes de dormir",
    modo_uso: "Infusão da raiz seca (2-3 g em água fervente por 10-15 min) ou cápsulas de extrato padronizado. Uso contínuo por pelo menos 2-4 semanas para efeito pleno.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/33086877/", "https://pubmed.ncbi.nlm.nih.gov/17145239/", "https://pubmed.ncbi.nlm.nih.gov/35378276/"],
    contraindicacoes: ["Gravidez e amamentação (dados insuficientes)", "Crianças menores de 3 anos", "Não usar antes de conduzir ou operar máquinas pesadas (possível sonolência)"],
    interacoes: "Pode potencializar efeitos de sedativos, benzodiazepínicos, barbitúricos e álcool. Possível interação com anestésicos.",
    efeitos_colaterais: "Geralmente bem tolerada. Raramente: dor de cabeça, tonturas, distúrbios gastrointestinais, sonolência diurna.",
    origem: "Fitoterapia Europeia",
    principios_ativos: ["Ácido valerênico", "Valepotriatos", "Isovaltrato", "GABA", "Lignanas"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Ginseng (Panax ginseng)",
    nome_chines: "人参 (Rén Shēn)",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Meta-análise de 2024 (15 RCTs, n=671) mostrou que o ginseng tem efeito significativo na melhoria da memória (SMD=0,19; IC 95% 0,02-0,36), especialmente em doses altas. Outra revisão sistemática e meta-análise (2022, 23 estudos) demonstrou que a suplementação com Panax ginseng reduziu significativamente os níveis de glicose, insulina, pressão arterial e colesterol total em comparação com placebo.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Fadiga física e mental; melhoria da memória e função cognitiva; suporte metabólico (glicemia, lipídios, pressão arterial)",
    dosagem: "200-400 mg de extrato padronizado (4-7% ginsenósidos) por dia, ou 1-2 g de raiz seca",
    modo_uso: "Cápsulas de extrato padronizado ou decocção da raiz seca (1-2 g fervidos por 15-20 min). Ciclos de 2-3 meses com pausas de 1 mês.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/39474788/", "https://pubmed.ncbi.nlm.nih.gov/35509826/", "https://pubmed.ncbi.nlm.nih.gov/34445021/"],
    contraindicacoes: ["Gravidez e amamentação", "Hipertensão arterial não controlada", "Doenças autoimunes", "Crianças menores de 12 anos"],
    interacoes: "Pode interagir com anticoagulantes (varfarina), antidiabéticos, inibidores da MAO e estimulantes. Evitar uso concomitante com cafeína em excesso.",
    efeitos_colaterais: "Insônia, dor de cabeça, distúrbios gastrointestinais, nervosismo, alterações na pressão arterial. Raramente: mastalgia, sangramento vaginal.",
    origem: "Medicina Tradicional Chinesa",
    principios_ativos: ["Ginsenósidos (Rb1, Rg1, Rg3)", "Panaxósidos", "Polissacarídeos", "Peptídeos"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Ginkgo biloba (Ginkgo biloba)",
    nome_chines: "银杏 (Yín Xìng)",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão sistemática e meta-análise (2015, 9 RCTs, n=2.561) demonstrou que o extrato EGb761 a 240 mg/dia estabiliza ou retarda o declínio cognitivo, funcional e comportamental em 22-26 semanas, com superioridade estatística especialmente em pacientes com sintomas neuropsiquiátricos. Meta-análise de 2023 (18 RCTs, n=1.642) confirmou que preparações de Ginkgo biloba combinadas com donepezila melhoram a taxa de eficácia clínica na doença de Alzheimer.",
    nivel_evidencia: "Moderada-Alta",
    aplicacoes_clinicas: "Défice cognitivo e demência (especialmente Alzheimer); melhoria da circulação periférica; zumbidos de origem vascular",
    dosagem: "120-240 mg de extrato padronizado EGb761 por dia, divididos em 2-3 tomas",
    modo_uso: "Comprimidos ou cápsulas de extrato padronizado (24% glicosídeos flavonoides, 6% terpenolactonas). Uso contínuo por pelo menos 8-12 semanas para avaliação de efeito.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/25114079/", "https://pubmed.ncbi.nlm.nih.gov/36960422/", "https://pubmed.ncbi.nlm.nih.gov/20236541/"],
    contraindicacoes: ["Distúrbios hemorrágicos ou coagulopatias", "Gravidez e amamentação", "Pré-operatório (suspender 2 semanas antes de cirurgia)", "Epilepsia (pode reduzir limiar convulsivo)"],
    interacoes: "Pode potencializar anticoagulantes e antiplaquetários (risco de hemorragia). Possível interação com antidepressivos ISRS, anticonvulsivantes e AINEs.",
    efeitos_colaterais: "Cefaleias, tonturas, distúrbios gastrointestinais, reações alérgicas cutâneas. Raramente: hemorragias.",
    origem: "Medicina Tradicional Chinesa",
    principios_ativos: ["Ginkgolídeos (A, B, C)", "Bilobalídeo", "Flavonoides (quercetina, kaempferol)", "Proantocianidinas"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Equinácea (Echinacea purpurea)",
    nome_chines: "",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão Cochrane de 2014 (24 RCTs duplo-cegos, n=4.631) concluiu que os produtos de Echinacea não demonstraram benefícios claros no tratamento de constipações, embora uma análise agrupada post hoc sugira redução de risco relativo de 10-20% na prevenção. Revisão sistemática de 2021 sobre efeitos imunomoduladores identificou que a Echinacea pode diminuir citocinas pró-inflamatórias (IL-6, IL-8, TNF) e aumentar a anti-inflamatória IL-10.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Prevenção e redução da duração de constipações e infecções do trato respiratório superior; suporte imunitário",
    dosagem: "300-500 mg de extrato padronizado 3x/dia, ou 2,5 mL de tintura 3x/dia",
    modo_uso: "Cápsulas, tintura ou infusão das partes aéreas. Iniciar ao primeiro sinal de constipação. Uso contínuo limitado a 8-10 semanas, com pausas.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/24554461/", "https://pubmed.ncbi.nlm.nih.gov/34341776/", "https://pubmed.ncbi.nlm.nih.gov/36364865/"],
    contraindicacoes: ["Doenças autoimunes (lúpus, esclerose múltipla, artrite reumatoide)", "Tuberculose e infecções por HIV", "Alergia a plantas da família Asteraceae", "Imunossupressão medicamentosa"],
    interacoes: "Pode interferir com imunossupressores (ciclosporina, corticoides). Possível interação com medicamentos metabolizados pelo CYP3A4.",
    efeitos_colaterais: "Geralmente bem tolerada. Raramente: reações alérgicas, náuseas, dor abdominal, erupções cutâneas.",
    origem: "Fitoterapia Norte-Americana",
    principios_ativos: ["Equinacósidos", "Ácido chicórico", "Alquilamidas", "Polissacarídeos", "Glicoproteínas"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Dente-de-Leão (Taraxacum officinale)",
    nome_chines: "蒲公英 (Pú Gōng Yīng)",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão abrangente de 2023 (Molecules) destacou múltiplas atividades farmacológicas comprovadas in vitro e em modelos animais, incluindo efeitos anti-inflamatórios, antioxidantes, hepatoprotetores e diuréticos. Revisão baseada em evidências (2005, Natural Standard) documentou o uso tradicional como diurético e hepatoprotetor, mas identificou escassez de ensaios clínicos de alta qualidade em humanos.",
    nivel_evidencia: "Baixa",
    aplicacoes_clinicas: "Efeito diurético leve; suporte à função hepática e digestiva; estimulação do apetite",
    dosagem: "4-10 g de raiz seca em decocção, 3x/dia, ou 2-5 mL de tintura (1:5) 3x/dia",
    modo_uso: "Infusão das folhas (para efeito diurético) ou decocção da raiz (para suporte hepático). Folhas frescas podem ser consumidas em saladas.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/16093238/", "https://pubmed.ncbi.nlm.nih.gov/37446683/", "https://pubmed.ncbi.nlm.nih.gov/35405251/"],
    contraindicacoes: ["Obstrução biliar ou cálculos biliares", "Úlcera gástrica ativa", "Alergia a plantas da família Asteraceae", "Gravidez (dados insuficientes)"],
    interacoes: "Pode potencializar diuréticos (risco de hipocalemia). Possível interação com lítio (redução da excreção renal), antibióticos quinolonas e antidiabéticos.",
    efeitos_colaterais: "Geralmente bem tolerado. Raramente: dermatite de contato, azia, diarreia, reações alérgicas.",
    origem: "Fitoterapia Europeia",
    principios_ativos: ["Taraxasterol", "Lactonas sesquiterpênicas", "Inulina", "Ácido chicórico", "Flavonoides (luteolina)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Espinheiro-alvar (Crataegus spp.)",
    nome_chines: "山楂 (Shān Zhā)",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão Cochrane de 2008 (14 RCTs, 10 estudos incluídos na meta-análise, n=855) demonstrou que o extrato de Crataegus como adjuvante ao tratamento convencional melhora significativamente a capacidade máxima de trabalho, tolerância ao exercício e sintomas como dispneia e fadiga na insuficiência cardíaca crônica (classes NYHA I-III). Efeitos adversos infrequentes, leves e transitórios.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Insuficiência cardíaca crônica leve a moderada (NYHA I-III); suporte cardiovascular; hipertensão leve",
    dosagem: "160-900 mg de extrato padronizado por dia (equivalente a 3,5-19,8 mg de flavonoides), divididos em 2-3 tomas",
    modo_uso: "Comprimidos ou cápsulas de extrato padronizado de folhas com flores. Pode ser usado como infusão (1-2 g de folhas/flores secas em 150 mL de água, 2-3x/dia). Uso contínuo por pelo menos 6-8 semanas.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/18254076/", "https://pubmed.ncbi.nlm.nih.gov/12597258/"],
    contraindicacoes: ["Não substituir tratamento convencional da insuficiência cardíaca", "Gravidez e amamentação (dados insuficientes)", "Crianças menores de 12 anos"],
    interacoes: "Pode potencializar efeitos de glicosídeos cardíacos (digoxina), anti-hipertensivos e vasodilatadores. Possível interação com inibidores da PDE5 (sildenafil).",
    efeitos_colaterais: "Náuseas, tonturas, palpitações, dor de cabeça, queixas gastrointestinais. Geralmente leves e transitórios.",
    origem: "Fitoterapia Europeia",
    principios_ativos: ["Vitexina", "Procianidinas oligoméricas (OPCs)", "Flavonoides (hiperoside, rutina)", "Ácidos triterpênicos (ácido ursólico)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Saw Palmetto (Serenoa repens)",
    nome_chines: "",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão Cochrane atualizada de 2012 (17 RCTs, n=2.008) concluiu que Serenoa repens em monoterapia não melhorou sintomas urinários (IPSS/AUASI) nem fluxo urinário máximo em comparação com placebo. Contudo, meta-análise de 2018 focada no extrato hexânico (Permixon, 27 estudos, n=5.800) mostrou redução significativa da noctúria (-0,64 episódios/noite) e melhoria do fluxo urinário (+2,75 mL/s) vs placebo, com eficácia comparável à tansulosina.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Hiperplasia benigna da próstata; sintomas do trato urinário inferior (LUTS); noctúria",
    dosagem: "320 mg de extrato lipídico padronizado por dia (em dose única ou 160 mg 2x/dia)",
    modo_uso: "Cápsulas moles de extrato lipídico hexânico padronizado, preferencialmente com refeições. Uso contínuo por pelo menos 4-6 semanas para avaliação de resposta.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/22551330/", "https://pubmed.ncbi.nlm.nih.gov/29694707/", "https://pubmed.ncbi.nlm.nih.gov/32274957/"],
    contraindicacoes: ["Gravidez e amamentação (efeito antiandrogênico)", "Mulheres em idade fértil", "Crianças"],
    interacoes: "Possível interação com anticoagulantes e antiplaquetários. Teoricamente pode interferir com contraceptivos orais e terapia hormonal.",
    efeitos_colaterais: "Geralmente bem tolerado. Raramente: desconforto gastrointestinal, náuseas, dor de cabeça, diminuição da libido.",
    origem: "Fitoterapia Norte-Americana",
    principios_ativos: ["Ácidos graxos (láurico, mirístico, oleico)", "Fitosteróis (beta-sitosterol)", "Flavonoides", "Polissacarídeos"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Cardo Mariano (Silybum marianum)",
    nome_chines: "",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Meta-análise de 2025 (55 RCTs, n=3.545) demonstrou que a silimarina reduz significativamente os níveis de AST (SMD=-0,670; p<0,001) e ALT (SMD=-0,912; p<0,001), com maior efeito em pacientes com NAFLD e hepatite viral, e em doses <400 mg por durações ≤2 meses. Revisão sistemática anterior (2008, 19 ensaios) encontrou redução significativa da mortalidade hepática na cirrose alcoólica (10% silimarina vs 17,3% placebo; p=0,01).",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Hepatoproteção; doença hepática gordurosa não alcoólica (NAFLD); hepatite viral; suporte na cirrose alcoólica; intoxicação por Amanita phalloides",
    dosagem: "200-400 mg de extrato padronizado (70-80% silimarina) por dia, divididos em 2-3 tomas",
    modo_uso: "Cápsulas ou comprimidos de extrato padronizado, tomados com refeições para melhor absorção. Curso de tratamento típico de 1-2 meses.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/40221681/", "https://pubmed.ncbi.nlm.nih.gov/18334810/", "https://pubmed.ncbi.nlm.nih.gov/35623810/"],
    contraindicacoes: ["Alergia a plantas da família Asteraceae", "Gravidez e amamentação (dados limitados)", "Condições hormônio-dependentes (efeito estrogênico teórico)"],
    interacoes: "Pode alterar metabolismo de fármacos via CYP2C9 e CYP3A4. Possível interação com estatinas, antirretrovirais, imunossupressores e anticoagulantes.",
    efeitos_colaterais: "Geralmente bem tolerada. Raramente: efeito laxante, náuseas, distensão abdominal, reações alérgicas.",
    origem: "Fitoterapia Europeia / Mediterrânea",
    principios_ativos: ["Silimarina (silibinina, silicristina, silidianina)", "Taxifolina", "Flavonolignanas", "Ácidos graxos"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Rhodiola (Rhodiola rosea)",
    nome_chines: "红景天 (Hóng Jǐng Tiān)",
    categoria: "Planta / Chá",
    categoria_slug: "planta",
    estudos_resumo: "Revisão sistemática de 2012 (11 ensaios) encontrou evidência preliminar de que a Rhodiola rosea pode ser benéfica para melhorar o desempenho físico e aliviar a fadiga mental, embora falhas metodológicas limitem a avaliação precisa. Revisão de 2022 (10 estudos) concluiu que a suplementação tem efeito positivo na capacidade atlética, reduzindo dor e dano muscular após exercício e melhorando a capacidade antioxidante.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Fadiga física e mental; adaptação ao estresse; melhoria do desempenho em exercício; suporte cognitivo em situações de estresse",
    dosagem: "200-600 mg de extrato padronizado (3% rosavinas, 1% salidrosídeo) por dia",
    modo_uso: "Cápsulas de extrato padronizado, preferencialmente de manhã ou antes de atividade física. Evitar tomar à noite (pode causar insônia). Ciclos de 6-10 semanas com pausas.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/22643043/", "https://pubmed.ncbi.nlm.nih.gov/35464040/", "https://pubmed.ncbi.nlm.nih.gov/34445021/"],
    contraindicacoes: ["Transtorno bipolar (risco teórico de mania)", "Gravidez e amamentação (dados insuficientes)", "Doenças autoimunes"],
    interacoes: "Possível interação com antidepressivos (ISRS, IMAO), estimulantes do SNC, antidiabéticos e anti-hipertensivos.",
    efeitos_colaterais: "Geralmente bem tolerada. Raramente: insônia, irritabilidade, boca seca, tonturas.",
    origem: "Medicina Tradicional Chinesa / Fitoterapia Nórdica-Siberiana",
    principios_ativos: ["Rosavinas (rosavina, rosina, rosarina)", "Salidrosídeo", "Tirosol", "Flavonoides", "Ácidos orgânicos"],
    ingredientes: [],
    faq: []
  }
];

// ============================================================
// 10 SUPLEMENTOS
// ============================================================
const suplementos = [
  {
    nome: "Complexo B (Vitaminas B1-B12)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises com mais de 46.000 participantes demonstram que a suplementação com vitaminas do complexo B pode retardar o declínio cognitivo e reduzir o risco de demência, especialmente em intervenções superiores a 12 meses. Evidências também sugerem benefício significativo na redução do estresse percebido, embora os efeitos sobre depressão e ansiedade sejam menos consistentes.",
    nivel_evidencia: "Moderada-Alta",
    aplicacoes_clinicas: "Prevenção do declínio cognitivo; redução de homocisteína elevada; suporte ao sistema nervoso; redução do estresse; suporte energético em casos de deficiência",
    dosagem: "Conforme formulação do complexo (tipicamente B1 25-100 mg, B2 25-100 mg, B3 25-50 mg, B5 25-100 mg, B6 25-50 mg, B7 300 mcg, B9 400-800 mcg, B12 250-1000 mcg)",
    modo_uso: "Tomar 1 cápsula ao dia com uma refeição, preferencialmente pela manhã.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/34432056/", "https://pubmed.ncbi.nlm.nih.gov/31527485/", "https://pubmed.ncbi.nlm.nih.gov/39952338/"],
    contraindicacoes: ["Hipersensibilidade a qualquer vitamina do complexo", "Doença de Leber (B12 isolada em altas doses)", "Consultar médico se em tratamento para epilepsia ou Parkinson"],
    interacoes: "Pode interagir com levodopa, fenitoína, fenobarbital e metotrexato. B6 em altas doses pode reduzir eficácia da levodopa.",
    efeitos_colaterais: "Geralmente bem tolerado. Em doses elevadas: náusea, diarreia, urina amarelada (riboflavina). B6 em doses >200 mg/dia por tempo prolongado pode causar neuropatia periférica.",
    origem: "Síntese laboratorial; encontradas naturalmente em cereais integrais, carnes, ovos, leguminosas e vegetais verdes",
    principios_ativos: ["Tiamina (B1)", "Riboflavina (B2)", "Niacina (B3)", "Ácido pantotênico (B5)", "Piridoxina (B6)", "Biotina (B7)", "Ácido fólico (B9)", "Cianocobalamina/Metilcobalamina (B12)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Ferro (Sulfato ferroso / Bisglicinato ferroso)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises abrangentes de 129 ensaios randomizados confirmam que a suplementação oral de ferro aumenta significativamente os níveis de hemoglobina (média de +2,0 g/dL) e reduz a prevalência de anemia ferropriva. Doses moderadas a altas e regimes intermitentes (1-2x/semana) mostraram-se eficazes e com menos efeitos colaterais gastrointestinais que doses diárias elevadas.",
    nivel_evidencia: "Alta",
    aplicacoes_clinicas: "Tratamento e prevenção de anemia ferropriva; fadiga associada a deficiência de ferro; suporte na gestação; melhora da função cognitiva em crianças com deficiência",
    dosagem: "Adultos: 30-65 mg de ferro elementar/dia (tratamento) ou 30 mg em dias alternados (prevenção). Crianças: conforme peso e gravidade",
    modo_uso: "Tomar preferencialmente em jejum ou entre refeições com vitamina C para melhorar absorção. Evitar tomar com café, chá, laticínios ou suplementos de cálcio.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/39951396/", "https://pubmed.ncbi.nlm.nih.gov/36849195/", "https://pubmed.ncbi.nlm.nih.gov/37368919/"],
    contraindicacoes: ["Hemocromatose ou outras condições de sobrecarga de ferro", "Anemias não ferroprivas (sideroblástica, hemolítica)", "Hemossiderose", "Doença hepática grave"],
    interacoes: "Reduz absorção de levotiroxina, tetraciclinas, quinolonas, bisfosfonatos e levodopa. Antiácidos e inibidores de bomba de prótons reduzem absorção do ferro.",
    efeitos_colaterais: "Náusea, constipação, diarreia, dor abdominal, fezes escurecidas. Bisglicinato ferroso tende a causar menos efeitos gastrointestinais que sulfato ferroso.",
    origem: "Síntese laboratorial; encontrado naturalmente em carnes vermelhas, fígado, leguminosas, vegetais verde-escuros",
    principios_ativos: ["Ferro elementar (como sulfato ferroso, bisglicinato ferroso, fumarato ferroso ou ferro quelato)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Selênio (Selenium)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises de ensaios clínicos randomizados demonstram que a suplementação de selênio reduz significativamente os níveis de anticorpos anti-tireoperoxidase (anti-TPO) em pacientes com tireoidite de Hashimoto. A combinação com mio-inositol pode potencializar os efeitos sobre os autoanticorpos tireoidianos. A evidência é consistente para a função tireoidiana, mas mista para outros desfechos.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Suporte na tireoidite autoimune de Hashimoto (redução de anti-TPO); proteção antioxidante; suporte ao sistema imunológico; saúde reprodutiva masculina",
    dosagem: "100-200 mcg/dia (selenometionina ou selenito de sódio). Não exceder 400 mcg/dia",
    modo_uso: "Tomar 1 cápsula ao dia com uma refeição. Uso contínuo deve ser monitorado por profissional de saúde.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/38243784/", "https://pubmed.ncbi.nlm.nih.gov/27702392/", "https://pubmed.ncbi.nlm.nih.gov/39650307/"],
    contraindicacoes: ["Hipersensibilidade ao selênio", "Selenose (intoxicação por selênio)", "Níveis séricos de selênio já elevados"],
    interacoes: "Pode interagir com medicamentos anticoagulantes, estatinas e niacina. Altas doses podem interferir com cisplatina e outros quimioterápicos.",
    efeitos_colaterais: "Em doses adequadas, geralmente bem tolerado. Doses excessivas (>400 mcg/dia) podem causar selenose: halitose com odor de alho, queda de cabelo, unhas quebradiças, náusea, diarreia, fadiga e irritabilidade.",
    origem: "Mineral-traço essencial; encontrado em castanha-do-pará, frutos do mar, carnes, ovos e cereais integrais",
    principios_ativos: ["Selênio (como selenometionina, selenito de sódio ou selenato de sódio)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "L-Teanina (L-Theanine)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Revisões sistemáticas e meta-análises de ensaios randomizados indicam que a L-teanina pode melhorar a qualidade do sono e promover relaxamento sem sedação. Estudos mostram efeitos positivos sobre a cognição e o humor, especialmente quando combinada com cafeína. A evidência para ansiedade clínica ainda é limitada, mas os efeitos sobre estresse e relaxamento são consistentes.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Redução do estresse e promoção de relaxamento; melhora da qualidade do sono; suporte à atenção e foco (especialmente com cafeína); redução de ansiedade leve",
    dosagem: "100-400 mg/dia. Para relaxamento: 200 mg. Para foco com cafeína: 100-200 mg de L-teanina + 50-100 mg de cafeína",
    modo_uso: "Tomar 30-60 minutos antes do momento desejado de relaxamento ou sono. Para foco, tomar junto com cafeína pela manhã. Pode ser fracionado em 2 doses diárias.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/40056718/", "https://pubmed.ncbi.nlm.nih.gov/40314930/", "https://pubmed.ncbi.nlm.nih.gov/35378276/"],
    contraindicacoes: ["Hipersensibilidade à L-teanina", "Gestantes e lactantes (dados insuficientes)", "Cautela em pacientes com hipotensão"],
    interacoes: "Pode potencializar efeitos de medicamentos anti-hipertensivos. Pode interagir com estimulantes e sedativos.",
    efeitos_colaterais: "Geralmente muito bem tolerada. Raramente: cefaleia leve, tontura ou desconforto gastrointestinal.",
    origem: "Aminoácido não proteico encontrado naturalmente nas folhas de chá verde (Camellia sinensis)",
    principios_ativos: ["L-teanina (ácido gama-glutamiletil amida)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Astaxantina (Astaxanthin)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises de ensaios clínicos randomizados indicam que a suplementação com astaxantina reduz moderadamente biomarcadores de estresse oxidativo e inflamação (como MDA e PCR). Revisões sistemáticas também sugerem efeitos favoráveis sobre o perfil lipídico e glicêmico, além de potenciais benefícios para saúde reprodutiva feminina.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Proteção antioxidante; redução de marcadores inflamatórios; suporte à saúde cardiovascular (perfil lipídico); saúde da pele (fotoproteção); saúde ocular (fadiga visual)",
    dosagem: "4-12 mg/dia",
    modo_uso: "Tomar com uma refeição que contenha gordura para melhorar a absorção (carotenoide lipossolúvel).",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/35091276/", "https://pubmed.ncbi.nlm.nih.gov/39127677/", "https://pubmed.ncbi.nlm.nih.gov/25995739/"],
    contraindicacoes: ["Hipersensibilidade à astaxantina ou frutos do mar", "Gestantes e lactantes (dados insuficientes)", "Cautela em pacientes com distúrbios autoimunes"],
    interacoes: "Pode potencializar efeitos de anti-hipertensivos e anticoagulantes. Pode interagir com inibidores de 5-alfa-redutase.",
    efeitos_colaterais: "Geralmente bem tolerada. Raramente: fezes avermelhadas (coloração do carotenoide), desconforto gastrointestinal leve.",
    origem: "Carotenoide produzido pela microalga Haematococcus pluvialis; também encontrado em salmão, camarão, krill e lagosta",
    principios_ativos: ["Astaxantina (3,3'-di-hidroxi-beta,beta-caroteno-4,4'-diona)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Feno-Grego (Trigonella foenum-graecum)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises demonstram que o extrato de feno-grego reduz significativamente os níveis de glicemia de jejum e hemoglobina glicada (HbA1c) em pacientes com diabetes tipo 2. Estudos também indicam efeito anabólico positivo, com aumento dos níveis de testosterona livre e melhora da composição corporal em homens que praticam exercício de resistência.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Controle glicêmico em diabetes tipo 2; aumento de testosterona livre em homens; suporte à lactação (galactagogo); melhora da composição corporal",
    dosagem: "500-1000 mg de extrato padronizado/dia. Para glicemia: 1-2 g de semente em pó. Para testosterona: 500-600 mg de extrato (ex: Testofen)",
    modo_uso: "Tomar com as refeições principais, dividido em 2-3 doses diárias. Para efeito sobre testosterona, uso contínuo por pelo menos 8-12 semanas.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/36837450/", "https://pubmed.ncbi.nlm.nih.gov/37253363/", "https://pubmed.ncbi.nlm.nih.gov/29193352/"],
    contraindicacoes: ["Gestantes (pode estimular contrações uterinas)", "Alergia a leguminosas (amendoim, grão-de-bico, soja)", "Hipoglicemia ou uso de antidiabéticos sem supervisão", "Distúrbios de coagulação"],
    interacoes: "Pode potencializar efeitos de hipoglicemiantes orais e insulina. Pode interagir com anticoagulantes (varfarina). Pode alterar absorção de medicamentos orais devido ao alto teor de fibra.",
    efeitos_colaterais: "Desconforto gastrointestinal (flatulência, diarreia, inchaço), odor característico na urina e suor (semelhante a xarope de bordo). Raramente: reações alérgicas.",
    origem: "Planta da família Fabaceae, nativa do Mediterrâneo e Ásia Ocidental; amplamente cultivada na Índia",
    principios_ativos: ["Saponinas esteroidais (diosgenina, protodioscina)", "4-hidroxiisoleucina", "Galactomananos", "Trigonelina"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Creatina (Creatine monohydrate)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises robustas demonstram que a suplementação de creatina combinada com treinamento de resistência aumenta significativamente a força muscular e a hipertrofia em adultos de todas as idades. A creatina monoidratada é o suplemento esportivo com maior evidência científica e perfil de segurança excelente a longo prazo. Evidências emergentes sugerem potenciais benefícios cognitivos.",
    nivel_evidencia: "Alta",
    aplicacoes_clinicas: "Aumento de força e massa muscular; melhora do desempenho em exercícios de alta intensidade; suporte cognitivo (especialmente sob privação de sono ou estresse); potencial benefício em doenças neurodegenerativas",
    dosagem: "Fase de manutenção: 3-5 g/dia de creatina monoidratada. Fase de carga opcional: 20 g/dia divididos em 4 doses por 5-7 dias",
    modo_uso: "Dissolver em água ou suco e tomar diariamente, independente do horário. Manter boa hidratação. Não necessita ciclagem.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/39519498/", "https://pubmed.ncbi.nlm.nih.gov/34836013/", "https://pubmed.ncbi.nlm.nih.gov/37432300/"],
    contraindicacoes: ["Doença renal pré-existente (usar com cautela e supervisão médica)", "Menores de 18 anos (dados limitados)"],
    interacoes: "Cautela com anti-inflamatórios nefrotóxicos. Pode potencializar efeitos de cafeína sobre o desempenho (evidência conflitante). Diuréticos podem aumentar risco de desidratação.",
    efeitos_colaterais: "Geralmente muito bem tolerada. Possível retenção hídrica inicial (1-2 kg), especialmente na fase de carga. Raramente: desconforto gastrointestinal, câimbras (sem evidência forte). Não causa dano renal em indivíduos saudáveis.",
    origem: "Composto nitrogenado sintetizado naturalmente no corpo a partir de arginina, glicina e metionina; encontrado em carnes vermelhas e peixes",
    principios_ativos: ["Creatina monoidratada"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "N-Acetilcisteína - NAC (N-Acetylcysteine)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análises de ensaios controlados demonstram que a NAC reduz significativamente biomarcadores inflamatórios (PCR, IL-6) e de estresse oxidativo. Revisões sistemáticas indicam benefício potencial como adjuvante no tratamento de transtornos psiquiátricos, incluindo depressão e TOC. A NAC também é amplamente utilizada como mucolítico e no tratamento de intoxicação por paracetamol.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Suporte antioxidante (precursor da glutationa); adjuvante em transtornos psiquiátricos (depressão, TOC, dependência química); mucolítico respiratório; hepatoprotetor; suporte na resistência insulínica",
    dosagem: "600-1800 mg/dia, divididos em 2-3 doses. Para uso psiquiátrico: 1000-2400 mg/dia",
    modo_uso: "Tomar com o estômago vazio ou com refeição leve. Dividir em 2-3 doses diárias para melhor tolerabilidade.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/32726657/", "https://pubmed.ncbi.nlm.nih.gov/39504621/", "https://pubmed.ncbi.nlm.nih.gov/39376972/"],
    contraindicacoes: ["Hipersensibilidade à acetilcisteína", "Úlcera péptica ativa (uso oral pode irritar mucosa gástrica)", "Asma grave (inalatório pode causar broncoespasmo)"],
    interacoes: "Pode potencializar efeitos de nitroglicerina (vasodilatação e cefaleia). Pode interagir com carbamazepina. Reduz nefrotoxicidade de contraste iodado. Antídoto para intoxicação por paracetamol.",
    efeitos_colaterais: "Náusea, vômito, diarreia, odor desagradável (enxofre). Raramente: cefaleia, erupção cutânea, broncoespasmo em asmáticos.",
    origem: "Derivado acetilado do aminoácido L-cisteína, obtido por síntese laboratorial",
    principios_ativos: ["N-acetilcisteína (N-acetil-L-cisteína)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Colina (Choline)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Revisões sistemáticas indicam que a colina desempenha papel fundamental no desenvolvimento neurológico durante os primeiros 1.000 dias de vida (gestação e primeira infância), influenciando a cognição e o neurodesenvolvimento. A suplementação durante a gravidez e lactação está associada a benefícios para o desenvolvimento cerebral fetal. A ingestão adequada é essencial para a função hepática e prevenção de esteatose.",
    nivel_evidencia: "Moderada",
    aplicacoes_clinicas: "Suporte ao neurodesenvolvimento fetal e infantil; saúde hepática (prevenção de esteatose); função cognitiva e memória; suporte na gestação e lactação; metabolismo de lipídios",
    dosagem: "Adultos: 425 mg/dia (mulheres) a 550 mg/dia (homens). Gestantes: 450-930 mg/dia. Formas comuns: colina bitartarato, citicolina (CDP-colina), alfa-GPC",
    modo_uso: "Tomar com refeições. Pode ser fracionado em 2 doses diárias. Citicolina e alfa-GPC são formas com melhor biodisponibilidade cerebral.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/32531929/", "https://pubmed.ncbi.nlm.nih.gov/37862810/", "https://pubmed.ncbi.nlm.nih.gov/29928762/"],
    contraindicacoes: ["Trimetilaminúria (síndrome do odor de peixe)", "Doença renal avançada", "Depressão grave (doses elevadas podem piorar em alguns casos)"],
    interacoes: "Pode interagir com inibidores da acetilcolinesterase (donepezila, rivastigmina). Metotrexato pode aumentar necessidade de colina.",
    efeitos_colaterais: "Em doses excessivas: odor corporal de peixe (trimetilamina), náusea, diarreia, vômito, sudorese excessiva, hipotensão. Doses adequadas são bem toleradas.",
    origem: "Nutriente essencial semelhante a vitaminas do complexo B; encontrado em ovos, fígado, carne bovina, soja, peixe e crucíferas",
    principios_ativos: ["Colina (como bitartarato de colina, citicolina/CDP-colina, alfa-GPC/alfa-glicerofosfocolina)"],
    ingredientes: [],
    faq: []
  },
  {
    nome: "Glutamina (L-Glutamine)",
    nome_chines: "",
    categoria: "Suplemento Ocidental",
    categoria_slug: "suplemento",
    estudos_resumo: "Meta-análise de ensaios clínicos demonstra que a suplementação de glutamina melhora significativamente a permeabilidade intestinal em adultos, sugerindo benefício para a integridade da barreira intestinal. Revisões sistemáticas em pacientes críticos indicam que a glutamina enteral pode reduzir complicações infecciosas. Estudos sobre recuperação muscular pós-exercício mostram resultados modestos e ainda inconclusivos.",
    nivel_evidencia: "Baixa-Moderada",
    aplicacoes_clinicas: "Suporte à integridade da barreira intestinal (permeabilidade intestinal aumentada); recuperação em pacientes críticos; suporte imunológico; recuperação pós-exercício intenso; síndrome do intestino permeável",
    dosagem: "5-20 g/dia. Para saúde intestinal: 5-10 g/dia. Para pacientes críticos: 0,3-0,5 g/kg/dia. Para exercício: 5-10 g no pós-treino",
    modo_uso: "Dissolver em água e tomar preferencialmente em jejum ou após exercício. Pode ser fracionado em 2-3 doses diárias. Uso contínuo por pelo menos 4-8 semanas para efeitos intestinais.",
    referencias: ["https://pubmed.ncbi.nlm.nih.gov/39397201/", "https://pubmed.ncbi.nlm.nih.gov/27440684/", "https://pubmed.ncbi.nlm.nih.gov/26545503/"],
    contraindicacoes: ["Encefalopatia hepática ou insuficiência hepática grave", "Hipersensibilidade à glutamina", "Síndrome de Reye", "Insuficiência renal grave (acúmulo de amônia)"],
    interacoes: "Pode interagir com anticonvulsivantes (pode reduzir eficácia de medicamentos que dependem do glutamato). Lactulose pode ter sua eficácia reduzida.",
    efeitos_colaterais: "Geralmente bem tolerada em doses adequadas. Em doses elevadas: inchaço abdominal, flatulência, náusea, cefaleia. Em pacientes com doença hepática, risco de aumento de amônia sanguínea.",
    origem: "Aminoácido condicionalmente essencial; o mais abundante no plasma sanguíneo. Obtido por fermentação bacteriana ou síntese",
    principios_ativos: ["L-glutamina"],
    ingredientes: [],
    faq: []
  }
];

// ============================================================
// INSERIR TUDO
// ============================================================
d.produtos.push(...oleos, ...plantas, ...suplementos);

// Recalcular categorias
const catCounts = {};
d.produtos.forEach(p => {
  const cat = p.categoria;
  catCounts[cat] = (catCounts[cat] || 0) + 1;
});
d.categorias = catCounts;
d.total_produtos = d.produtos.length;

fs.writeFileSync(jsonPath, JSON.stringify(d, null, 2), 'utf8');

console.log('Total produtos:', d.total_produtos);
console.log('Categorias:', JSON.stringify(catCounts, null, 2));
console.log('\nAdicionados:');
console.log('  Óleos essenciais:', oleos.length);
console.log('  Plantas:', plantas.length);
console.log('  Suplementos:', suplementos.length);
